### ISSUE TITLE
dashboard --> credits

### ISSUE THREAD

**Issue by divyatiwari5** [civilmachines/Rekrutify_Empoyer_IssueTracker#24]
![credits](https://user-images.githubusercontent.com/13404776/41595535-bed72bb0-73e4-11e8-9626-fd54cd2aedcd.png)

I think in Bronze, Job Posting value should be NO and in GOLD, it should be  YES

**Comment by jst-vikrant** [comment]
actually we are giving high credits in gold plan so thats why job posting is not involved in gold one.
